version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(npm):"
    groups:
      typescript:
        patterns:
          - "typescript"
          - "typedoc"
          - "@types/*"
      lint:
        patterns:
          - "@types/eslint__js"
          - "@eslint/*"
          - "@stylistic/eslint-plugin"
          - "eslint*"
          - "publint"
          - "typescript-eslint"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-*"
          - "vitest"
          - "@vitest/*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(gha):"
    groups:
      actions-deps:
        patterns:
          - "*"  
    open-pull-requests-limit: 10
 
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
       interval: "weekly"
    commit-message:
       prefix: "deps(docker):"
    open-pull-requests-limit: 10
