services:
  frontend:
    container_name: frontend
    image: upload_frontend:latest
  #  ports:
  #   - 80:80/tcp
    restart: always  
    healthcheck:
      test: service nginx status || exit 1
      interval: 5m
      timeout: 5s
      retries: 3
    env_file:
    - dev.env
    #- prod.env  
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.tls=false
      - traefik.http.services.frontend-service.loadbalancer.server.port=80